name: This a workflow title
on:
  push:
    branches:
      - main

  jobs:
    jobggg_1:
      name: push image
      - steps:
        name: docker login
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
